language: r
warnings_are_errors: false
cache:
  packages: true
script:
- Rscript -e "rmarkdown::render_site()"
after_success:
- curl -OL http://raw.githubusercontent.com/soztag/fau_deploy/master/deploy2karli.sh
deploy:
- provider: pages
  skip_cleanup: true
  github_token: "$GITHUB_TOKEN"
  local_dir: _site/
  commiter-grom-gh: true
  on:
    branch: master
- provider: script
  skip_cleanup: true
  script:
  - bash deploy2karli.sh
  on:
    branch: master
notifications:
  email: false
before_deploy:
- openssl aes-256-cbc -K $encrypted_38422806b665_key -iv $encrypted_38422806b665_iv
  -in karli_rsa.enc -out /tmp/karli_rsa -d
